### ISSUE TITLE
Support KSQL and Kafka Connect

### ISSUE THREAD

**Issue by ChethanUK** [banzaicloud/kafka-operator#109]
**Is your feature request related to a problem? Please describe.**
Support Kafka Connect and KSQL

**Describe the solution you'd like to see**
KSQL: SQL on Kafka
Kafka Connect: Support a wide variety of Databases: https://github.com/Landoop/stream-reactor/releases

**Comment by baluchicken** [comment]
Hi @ChethanUK 
Unfortunately we cannot add KSQL, Kafka Connect, Kafka Schema Registry support to our Operator because these are Confluent products with [Confluent Community License](https://github.com/confluentinc/ksql/blob/master/LICENSE). 
Our understanding of this license forbids other companies other than Confluent to distribute these products including installing and configuring it automatically. (Believe me it is the least understandable license we ever saw but it's there.) 
However, the license also says an end user/company can use it freely. 
Since BanzaiCloud's Kafka Operator installs vanilla Kafka, technically all these products can work seamlessly with it. Confluent does not leave other choice but to use the official Confluent helm [charts](https://github.com/confluentinc/cp-helm-charts) to install the required products.
On the other hand we believe in separation of concerns - the role of the operator is install and manage Kafka, all other ecosystem products should be installed separately.

**Comment by welcomemandeep** [comment]
AFAIK, Kafka Connect framework itself is part has Apache 2.0 license. Only the Confluent supported plugins are Confluent Community licensed.  So we can add support for Kafka Connect, no?

**Comment by matyix** [comment]
Kafka connect framework is already natively supported by Kafka (https://kafka.apache.org/documentation/#connect) and the operator - it’s the plugins which might fall under licensing. For example in [Supertubes](https://banzaicloud.com/products/supertubes/) we use Mirror Maker 2 which uses Connect behind the scene. We don’t indent to add plugins to the operator, but you can just do that fine.

For Kafka Connect reference, see the `/opt/kafka/bin/connect-standalone` in the Docker image.

**Comment by welcomemandeep** [comment]
@matyix  I was asking for an operator for Kafka Connect Workers.

> `/opt/kafka/bin/connect-standalone`

I think you are referring to `connect-distributed` which would be more relevant in this case.  My ask was to create first-class support for Connect Entities as well. ( like some other operators have)
