### ISSUE TITLE
cert-manager changed their API group

### ISSUE THREAD

**Issue by BradLugo** [banzaicloud/kafka-operator#170]
**Describe the bug**
Starting from [cert-manager v0.11.0](https://github.com/jetstack/cert-manager/releases/tag/v0.11.0), the project changed the API group and bumped the API version. This causes validation errors when installing kafka-operator's Helm chart. After searching this repo for `certmanager.k8s.io`, it seems the Helm chart, the kustomize config files, and some code will need to be updated to accomdate cert-manager's changes.

Here's the exact Helm error:
```console
$ helm install --name kafka-operator banzaicloud-stable/kafka-operator
Error: validation failed: [unable to recognize "": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1", unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"]
```

**Steps to reproduce the issue:**
Install cert-manager v0.11.0 via the [Helm chart](https://github.com/jetstack/cert-manager/tree/master/deploy/charts/cert-manager) (in theory, you only need the cert-manager crds to reproduce this issue)
```console
$ kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml
$ helm repo add jetstack https://charts.jetstack.io
$ helm install --name cert-manager jetstack/cert-manager
```

Install kafka-operator via the [Helm chart](https://github.com/banzaicloud/kafka-operator/tree/master/charts/kafka-operator)
```console
$ helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
$ helm install --name kafka-operator banzaicloud-stable/kafka-operator
```

**Comment by tinyzimmer** [comment]
This was on the radar already when I noticed that API change on their master branch a few weeks ago, but I already had a giant PR I was in the middle of getting through. The instructions in the README should be using `0.10.1` at the moment. 

Like you said it'll need to be updated in a few places (the new KafkaUser stuff uses it in addition to the webhook). It shouldn't be too hard because when I looked at it last there wasn't really much _breaking_ about the API change, more just the version bump.
