### ISSUE TITLE
Use existing cert-manager

### ISSUE THREAD

**Issue by palmerabollo** [banzaicloud/kafka-operator#183]
It would be great if you could use an existing cert-manager instance.

However, the README says you need to create a cert-manager namespace and deploy a cert-manager instance (and its CRDs). Would it be possible to use an existing cert-manager if you already have one running in a different namespace? It looks like it's [hardcoded here](https://github.com/banzaicloud/kafka-operator/blob/449f0a60cccb9c8ccae6ecd1369fd0ac4e98d26d/pkg/pki/certmanagerpki/certmanager_pki.go#L38) :(

This issue is related to #160 (existing Prometheus setup).
Thank you.

**Comment by tinyzimmer** [comment]
As you pointed out this is hard-coded at the moment, and IIRC it's because the `Certificate` used by a `ClusterIssuer` needs to be in the same namespace as the `cert-manager` deployment. A `ClusterIssuer` is used so that `KafkaUser`'s can be provisioned across any namespace. 

It would be possible to use a pre-existing namespace, perhaps by making the value configurable via a CLI switch or Environment Variable, and have it default back to `cert-manager` if not provided.

**Comment by baluchicken** [comment]
The fix for this just went in #180.
