### ISSUE TITLE
Issues deleting KafkaCluster

### ISSUE THREAD

**Issue by VishwasKumar** [banzaicloud/kafka-operator#262]
Trying out the example KafkaCluster (simplekafkacluster.yaml), I am not able to delete the cluster. I see the following logs on the operator:

 manager {"level":"info","ts":1579893801.152252,"logger":"controllers.KafkaCluster","msg":"Reconciling KafkaCluster","kafkacluster":"kafka/kafka","Request.Name":"kafka"}
manager {"level":"info","ts":1579893801.1522722,"logger":"controllers.KafkaCluster","msg":"KafkaCluster is marked for deletion, checking for children","kafkacluster":"kafka/kafka","Request.Name":"kafka"}
manager {"level":"info","ts":1579893801.1523893,"logger":"controllers.KafkaCluster","msg":"Ensuring all topics have finished cleaning up","kafkacluster":"kafka/kafka","Request.Name":"kafka"}               manager 
{"level":"info","ts":1579893801.1524088,"logger":"controllers.KafkaCluster","msg":"Still waiting for the following topics to be deleted: [kafka/kafka-cruise-control-topic]","kafkacluster":"kafka/kafka","Request.Name":"kafka"}

- I have already tried to delete all zookeepers along with their PVCs and reinstalled the cluster.
- Using the kafka client I don't see any topic called "kafka/kafka-cruise-control-topic"

Any suggestions why this is happening or to force delete the topic?

**Comment by stoader** [comment]
You shouldn't delete ZK until all resources are cleaned up as ZK is required by Kafka. Is there anything suspicious in your  Kafka brokers and Cruise Control logs? The operator waits until Kafka successfully deleted the topic and only after that deletes the KafkaTopic CRs.

In order to force delete the KafkaTopic CR remove the finalizers from it.

**Comment by VishwasKumar** [comment]
I don's see anything suspicious in either the broker logs or the cruise control logs. 

But I could reproduce this issue when I deleted the kafka-operator before deleting the `KafkaCluster` CR. This meant the `kafkaclusters.kafka.banzaicloud.io` CRD gets stuck with Status `Terminating` until I remove the finalizers from the CR. 

Seems like a problem with how the deleting of the kafka cluster and operator was orchestrated

Thanks for your help.

**Comment by stoader** [comment]
Since `kafka-operator` deletes the resources you should delete kafka-operator only after it cleaned up all resources.

**Comment by goddini91** [comment]
After remove all resurce kafka-cluster and zk and  Cruise Control kafkaclusters.kafka.banzaicloud.io state at status Terminating and I can't reinstall  kafka-operator

**Comment by stoader** [comment]
@goddini91 What do you mean by ```After remove all resurce kafka-cluster and zk and Cruise Control```?

Did you remove these manually?

**Comment by goddini91** [comment]
I used helm del --purge kafka-operator
Now for new installing get message "being deleted: customresourcedefinitions.apiextensions.k8s.io "kafkatopics.kafka.banzaicloud.io" already exists"
kubectl delete crd kafkatopics.kafka.banzaicloud.io not help

**Comment by baluchicken** [comment]
Hi, @goddini91 the operator uses finalizers to ensure that the K8s resource is not deleted before the operator removes all external dependencies. You cannot delete the `kafkatopics.kafka.banzaicloud.io` since there is still a k8s resource which uses that type. 
From the command log you posted my guess is that the `kafka-cruise-control-topic` topic resource is still in terminating state. Please edit that resource and remove the finalizer from it. With the finalizer removed the Kubernetes will be able to delete that resource, and the CRD as well.
I hope this solves your problem

**Comment by goddini91** [comment]
@baluchicken  @stoader  thank you
