### ISSUE TITLE
Add (z)etcd operator as a drop-in replacement for Zookeeper

### ISSUE THREAD

**Issue by yarncraft** [banzaicloud/kafka-operator#362]
**Is your feature request related to a problem? Please describe.**
I read the blogpost on using _etcd_ as a Zookeeper replacement (https://banzaicloud.com/blog/kafka-on-etcd/) but I saw you are still using ZooKeeper in this setup. Etcd sparked my interest given the benchmarks of CoreOS (https://coreos.com/blog/performance-of-etcd.html) which clearly states the CPU/RAM overhead of the JVM when running Zookeeper.

**Describe the solution you'd like to see**
Is it possible to provide **_a zetcd operator_** as drop-in replacement for the ZooKeeper operator you are using at the moment and add it to the installation documentation. The operator could be based on the zetcd Helm chart (https://github.com/helm/charts/tree/master/stable/zetcd). Given that your organisation already has experience in doing this, I think this feature would really stand out when compared to the Kafka operator of Strimzi (https://github.com/strimzi/strimzi-kafka-operator).

Thanks in advance.

**Comment by matyix** [comment]
I believe there are [way more](https://banzaicloud.com/blog/kafka-operator/) (and the list has just grown since) stand out features than this as suggested but for the context:

- yes, we _internally_ use etcd instead of ZK but from operational standpoint it brings new issues for those not familiar with K8s (and etcd in special), e.g. [multi-tenancy](https://banzaicloud.com/blog/etcd-multi/), backups, etc.
- at the time we published the afore mentioned post, the intent was to push it back upstream, but the community was not open for it. See the KIP we have created [KIP-273](https://cwiki.apache.org/confluence/display/KAFKA/KIP-273+-+Kafka+to+support+using+ETCD+beside+Zookeeper)
- if there is no community around, no adoption and minimal demand it does not make too much sense to support such a feature (note that we use it internally because we see the benefits but do not want to support this for our users/customers)
- zetcd it's just a bridge, there is no need for an operator 
- the Kafka community finally realized how big pain ZK is and it's working on a ZKless kafka (see the [KIP}(https://issues.apache.org/jira/browse/KAFKA-9119) and the [JIRA](https://issues.apache.org/jira/browse/KAFKA-9119). 

These above, but especially the last one will make the (z)etcd approach redundant and I would not suggest you to invest any effort into this. Btw, our own internal reasons for replacing ZK was never the mentioned performance - in a *real* Kafka cluster, compared to the cluster resources it's fractional. 

What is your motivation to replace ZK, would you mind sharing it? Is the performance mentioned above causes you issues? Note that Kafka is not using ZK as heavily as indicated in the performance test, that was using ZK merely as a KV store. Are you running a Kafka/ZK cluster on Kubernetes and you have any issues?

**Comment by yarncraft** [comment]
Ok thanks for the information!

- I actually meant an etcd operator with a zetcd helm chart similar to the one referenced, the CoreOS operator was (unfortunately) archived (https://github.com/coreos/etcd-operator).
- The replacement was just out of professional curiosity regarding etcd in distributed systems
- At the moment we're running on _Confluent Cloud_ without any issues
