### ISSUE TITLE
Labels not getting updated for PVCs during reconciliation

### ISSUE THREAD

**Issue by ecojan** [banzaicloud/kafka-operator#573]
**Describe the bug**
Having a cluster up and running using 1 PVC per broker and with propagateLabels set to true. When adding a new label to the KafkaCluster CR nothing happens at first (and its expected behavior) but after deleting a broker pod, a reconciliation is triggered and the new label is added to all resources except PVCs.

Replacing the PVC or adding new ones seems to add the new label though.

I tried putting the operator in verbose mode to see debug logs, I do see it trying to patch the PVC but I am not sure why it has no effect.

Is this something known or expected?

**Steps to reproduce the issue:**
Create a simple cluster with at least 2 brokers with 1 PVC each broker and with `propagateLabels` set to true. Wait until it reaches the "Cluster running" state. Edit the KafkaCluster CR, add a new label and delete a pod after to trigger a reconciliation.

**Expected behavior**
All resources managed for the KafkaCluster to receive the new set of labels.

**Additional context**
Using the latest version.

**Comment by baluchicken** [comment]
Hi @ecojan thanks for opening this ticket and sorry for the late response. We just identified the bug and going to fix this soon.

**Comment by ecojan** [comment]
Hi @baluchicken , what was the issue itself? I am quite curious, tried figuring it out myself but didn't manage to reach the source of the bug

**Comment by baluchicken** [comment]
@ecojan we are coping everything from the current pvc expect the resource requests.
https://github.com/banzaicloud/kafka-operator/blob/39b8b0f682a622a46b32bc43e1e00bb5179da678/pkg/resources/kafka/kafka.go#L747
Since PVC has multiple immutable fields and I am not aware of any documentation about this it is little challenging to figure out which values are suitable for update. I will add the annotations and labels here for now. Expect PR soon.
